function fig = BS_IndexMenu()
% function fig = BS_IndexMenu()
%
% Set up menu for indexing and resampling 'Bubblesim' result files
%

% Lars Hoff
% NTNU, Dept. of Telecommunications, N-7491 Trondheim

%--- Positions ---

offset= 50;
pbx   = offset+150*[ 0:2];
for k=1:length(pbx)
  pos.pb{k} = [ pbx(k) 20 120 30 ];
end
fullwidth = max(pbx)-pbx(1)+120;

texty= [100 130 ];
for k=1:length(texty)
  pos.text{k}  = [ offset texty(k) fullwidth 20];
end

pos.waitbar= [ offset  70 fullwidth 20];
pos.head   = [ offset 160 fullwidth 25];

pos.fig  = [600 600 fullwidth+2*offset 200 ];

%--- Colors ---
background = 0.80*[1 1 1];


%--- Figure definition ---
h0 = figure('Units','pixels', ...
        'Name', 'Reduce and Sort Results', ...
        'NumberTitle', 'Off', ...
	'Color',background, ...
	'Position', pos.fig );

%--- Header ---
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',background, ...
  	'FontUnits','pixels', ...
	'FontSize',16, ...
	'FontWeight','bold', ...
	'Position', pos.head, ...
	'String','Reorganize Simulation Results', ...
	'Style','text' );

%--- Pushbuttons ---
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'Callback','indexresults', ...
	'Position', pos.pb{1}, ...
	'String','Index results', ...
        'Style', 'pushbutton' );
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'Callback','reducedatafiles', ...
	'Position', pos.pb{2}, ...
	'String','Remove fields', ...
        'Style', 'pushbutton' );
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'Callback','calculatespectra', ...
	'Position', pos.pb{3}, ...
	'String','Calculate spectra', ...
        'Style', 'pushbutton' );

%--- Text fields ---
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Position',pos.text{2}, ...
	'Style','text', ...
        'Tag', 'resultpath' );
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Position',pos.text{1}, ...
	'Style','text', ...
        'Tag', 'message' );

%--- Waiting indicator ---
h1 = axes( 'Units','pixels', ...
           'Box','on', ...
           'Position', pos.waitbar, ...
           'Tag', 'waitbar', ...
           'XLim',[ 0 1 ],            'YLim',[ 0 1 ], ...
           'XTickMode','manual',      'YTickMode','manual',...
           'XTick',[],                'YTick',[],...
           'XTickLabelMode','manual', 'YTickLabelMode','manual',...
           'XTickLabel',[],           'YTickLabel',[]);

updatewaitbar(0);


if nargout > 0, fig = h0; end



