function fig = BS_BubbleMenu()
% function fig = BS_BubbleMenu()
%
% Simulate oscillation of bubble in acoustic field
%
% Main program
% Set up simulation menu

% Lars Hoff, NTNU, Dept. of Telecommunications
% Trondheim, Norway

global nano micro milli centi kilo Mega

%=== BASIC DEFINITIONS =====================================
nano  = 1e-9;
micro = 1e-6;
milli = 1e-3;
centi = 1e-2;
kilo  = 1e3;
Mega  = 1e6;

%=== CALCULATION OPTIONS ===================================
BS_WriteFunctionname

%--- ODE solvers ---
ODEsolver= struct( ...
           'name',    {'Runge-Kutta 4-5 order' 
		               'Stiff. Variable order'}, ...
                       'command', {'ode45'
		               'ode15s'} );

%--- Simulation models ---
model= struct( ...
        'name', {'Rayleigh-Plesset'
		'R-P with Radiation Damping'
		'Trilling'
		'Keller-Miksis' }, ...
        'ode',  {'Rayleigh'
		'ModifiedRayleigh'
		'Trilling'
		'Keller' } );

%--- Thermal damping options ---
thermaldamping= struct( ...
                'name',    {'Isothermal'
			    'Adiabatic'
 			    'Thermal damping. Pulse freq.'
			    'Thermal damping. Res. freq.' }, ...
                'command', {'isothermal'
			    'adiabatic'
			    'pulsefrequency'
			    'resonancefrequency' } );

%--- Liquids ---
liquid= struct( ...
                'name',    {'Water'
			    'Blood'} );

%--- Pulse types ---
pulsetype= struct ( ...
           'name',     {'Load from file'
			'Rectangular'
			'Cos-tapered rect.'
			'Triangular'
			'Hanning'
			'Hamming'
			'Blackman' }, ...
           'command', {{'LoadFile',    0   }
		       {'rectangular', 0   }
		       {'costapered',  0.2 }
		       {'triangular',  0   }
		       {'hanning',     0   }
		       {'hamming',     0   }
		       {'blackman',    0   }} );

%=== DEFINE SIZES ==========================================
ht= 14;   % Text height

%--- Labels ---
xl = 45;
wl = 125;
hl = ht;

%--- Edit boxes ---
xe = xl+wl;
we = 40;

%--- Pop-up menus ---
wp = 120;
dp = wp-we;
xp = xe-dp;

%--- Check boxes ---
wc = 100;
xc = xp+wp+35;

%--- Command buttons ---
wb = 80;
xb = [xp xc];
hb = 1.2*ht;

%--- Header ---
xh = xp;
wh = xb(2)+wb-xh;

%--- Figure size ---
set (0, 'units', 'points' );
screensize = get (0, 'screensize');
xf = floor(screensize(3)/100);
wf = xc+wc+20;

%--- Message fields ---
xm = xp;%+2*we;
wm = wf-xm;

%--- y-positions ---
dyl= 2;
ye = [60:17:900];       %  Edit boxes
yl = ye-dyl;            %  Labels
yc = ye(5:length(ye));  %  Check boxes
yp = ye([ 10 12:18]);   %  Pop-up menus
yb = ye(17);            %  Command buttons
yh = ye(19);            %  Headers
ym = ye(1)-[25 40 55];  %  Messages

hf = max(yh)+1.4*ht;
yf = screensize(4)-hf-30;

background     = 0.85*[1 1 1];
textbackground = [1 1 1];

%=== DEFINE MENU ===================================

%--- Figure window ---
h0 = figure('Color', background, ...
	    'Name', 'Bubble Oscillation', ...
	    'MenuBar', 'none', ...
	    'NumberTitle', 'off',...	
	    'Units', 'points', ...
	    'Position',[xf yf wf hf ] );

set ( h0, 'DefaultUIcontrolUnits',               'points', ...
	  'DefaultUIcontrolHorizontalAlignment', 'right', ...
	  'DefaultUIcontrolBackgroundColor',      background, ...
	  'DefaultUIcontrolFontSize',             8, ...
	  'DefaultUIcontrolFontWeight',          'normal' );

%--- Header ---
h1= uicontrol(...
	'Parent', h0, ...
	'FontWeight', 'bold', ...
	'FontSize', 10 , ...
	'Position', [xh yh(1) wh ht], ...
	'String', 'Simulate Bubble Oscillation', ...
        'HorizontalAlignment', 'center', ...
	'Style', 'text', ...
	'Tag', 'Header' );

%--- Messages ---
h1= uicontrol(...
        'Parent',h0, ...
	'FontWeight', 'Bold', ...
	'Position',[xm ym(3) wm ht], ...
        'HorizontalAlignment', 'left', ...
	'Style','text', ...
	'Tag','warning');

h1= uicontrol(...
        'Parent',h0, ...
	'FontWeight', 'Bold', ...
	'Position',[xm ym(2) wm ht], ...
        'HorizontalAlignment', 'left', ...
	'Style','text', ...
	'Tag','message');

h1= uicontrol('Parent',h0, ...
	'Position',[xm ym(1) wm ht], ...
        'HorizontalAlignment', 'left', ...
	'Style','text', ...
	'Tag','functionname');

%--- Command buttons ---
h1= uicontrol(... 
	'Parent',h0, ...
	'Callback','[particle,pulse,linear,simulation,graph]=BS_BubblesimCallback(''display'');', ...
	'Position',[xb(1) yb(1) wb hb ], ...
	'String','Display Pulse', ...
	'Tag','DefinePulse');

h1= uicontrol(... 
         'Parent',h0, ...
	'Callback','[particle,pulse,linear,simulation,graph]=BS_BubblesimCallback(''calculate'');', ...
	'Position',[xb(2) yb(1) wb hb ], ...
	'String','Calculate', ...
	'Tag','Calculate');

%--- Pop-up menus ---
h1= uicontrol(...
        'Parent',h0, ...
	'BackgroundColor',textbackground, ...
	'Position',[xp yp(5) wp ht], ...
	'String',{ODEsolver.name}, ...
	'Style','popupmenu', ...
	'Tag','ODEsolver', ...
	'UserData',ODEsolver, ...
	'Value',2);

h1= uicontrol(...
	'Parent',h0, ...
	'BackgroundColor',textbackground, ...
	'Position',[xp yp(4) wp ht], ...
	'String',{model.name}, ...
	'Style','popupmenu', ...
	'Tag','ODE', ...
	'UserData',model, ...
	'Value',2);

h1= uicontrol(... 
        'Parent',h0, ...
	'BackgroundColor',textbackground, ...
	'Position',[xp yp(3) wp ht], ...
	'String',{thermaldamping.name}, ...
	'Style','popupmenu', ...
	'Tag','ThermalDamping', ...
	'UserData',thermaldamping, ...
	'Value',1);

h1= uicontrol(... 
        'Parent',h0, ...
	'BackgroundColor',textbackground, ...
	'Position',[xp yp(2) wp ht], ...
	'String',{liquid.name}, ...
	'Style','popupmenu', ...
	'Tag','Liquid', ...
	'UserData',liquid, ...
	'Value',1);

h1= uicontrol(... 
        'Parent',h0, ...
	'BackgroundColor',textbackground, ...
	'Position',[xp yp(1) wp ht], ...
	'String',{pulsetype.name}, ...
	'Style','popupmenu', ...
	'Tag','Pulsetype', ...
	'UserData',pulsetype, ...
	'Value',5);

%--- Pop-up menu labels ---
h1= uicontrol(... 
         'Parent',h0, ...
	'Position',[xl-dp yp(5)-dyl wl ht], ...
	'String','ODE Solver   ', ...
	'Style','text');

h1= uicontrol(... 
        'Parent',h0, ...	
	'Position',[xl-dp yp(4)-dyl wl ht], ...
	'String','Liquid Model   ', ...
	'Style','text');

h1= uicontrol(... 
        'Parent',h0, ...	
	'Position',[xl-dp yp(3)-dyl wl ht], ...
	'String','Gas Model   ', ...
	'Style','text');

h1= uicontrol(... 
        'Parent',h0, ...	
	'Position',[xl-dp yp(2)-dyl wl ht], ...
	'String','Liquid   ', ...
	'Style','text');

h1= uicontrol(... 
        'Parent',h0, ...	
	'Position',[xl-dp yp(1)-dyl wl ht], ...
	'String','Pulse Envelope   ', ...
	'Style','text');

%--- Edit boxes ---
h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(9) we ht], ...
	'String','0.3', ...
	'Style','edit', ...
	'Tag','Amplitude');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(8) we ht], ...
	'String','2.5', ...
	'Style','edit', ...
	'Tag','Ncycles');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(7) we ht], ...
	'String','2.25', ...
	'Style','edit', ...
	'Tag','f0');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(6) we ht], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','fs');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(4) we ht], ...
	'String','1.5', ...
	'Style','edit', ...
	'Tag','Radius');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(3) we ht], ...
	'String','0.0', ...
	'Style','edit', ...
	'Tag','ShellThickness');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(2) we ht], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','ShellShearModulus');

h1= uicontrol(... 
        'Parent',h0, ...	
	'BackgroundColor',textbackground, ...
	'HorizontalAlignment','left', ...
	'Position',[xe ye(1) we ht], ...
	'String','0.0', ...
	'Style','edit', ...
	'Tag','ShellViscosity');

%--- Edit box labels ---
h1= uicontrol(... 
	             'Parent',h0, ...	
	'Position',[xl yl(9) wl hl], ...
	'String','Pulse Amplitude [MPa]   ', ...
	'Style','text');

h1= uicontrol(... 
        'Parent',h0, ...	
	'Position',[xl yl(8) wl hl], ...
	'String','Pulse Length [Cycles]   ', ...
	'Style','text' );

h1= uicontrol(... 
	             'Parent',h0, ...	
	'Position',[xl yl(7) wl hl], ...
	'String','Pulse Center Freq. [MHz]   ', ...
	'Style','text' );

h1= uicontrol(... 
	 'Parent',h0, ...	
	'Position',[xl yl(6) wl hl], ...
	'String','Sample Rate [MHz]   ', ...
	'Style','text');

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xl yl(4) wl hl], ...
	'String','Bubble Radius [um]   ', ...
	'Style','text');

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xl yl(3) wl hl ], ...
	'String','Shell Thickness  [nm]   ', ...
	'Style','text');

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xl yl(2) wl ht], ...
	'String','Shell Shear Modulus [MPa]   ', ...
	'Style','text');

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xl yl(1) wl ht], ...
	'String','Shell Viscosity [Pas]   ', ...
	'Style','text');

%--- Check boxes ---
h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(10) wc ht], ...
	'String','Display Progress', ...
	'Style','checkbox', ...
	'Tag','DisplayProgress', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xc yc(9) wc ht], ...
	'String','Inverted Pulse', ...
	'Style','checkbox', ...
	'Tag','Inversion');

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(8) wc ht], ...
	'String','Linear Calculations', ...
	'Style','checkbox', ...
	'Tag','PlotLinear', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...	
	'Position',[xc yc(6) wc ht], ...
	'String','Driving Pulse', ...
	'Style','checkbox', ...
	'Tag','PlotIncoming', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(5) wc ht], ...
	'String','Scattered Pulse', ...
	'Style','checkbox', ...
	'Tag','PlotScattered', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(4) wc ht], ...
	'String','Radius', ...
	'Style','checkbox', ...
	'Tag','PlotRadius', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(3) wc ht], ...
	'String','Velocity', ...
	'Style','checkbox', ...
	'Tag','PlotVelocity');

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(2) wc ht], ...
	'String','Power Spectra', ...
	'Style','checkbox', ...
	'Tag','PlotSpectra', ...
	'Value',1);

h1= uicontrol(... 
	'Parent',h0, ...
	'Position',[xc yc(1) wc ht], ...
	'String','Transfer Functions', ...
	'Style','checkbox', ...
	'Tag','PlotTransfer');

if nargout > 0, fig = h0; end

return



